services:
  iris_null:
    container_name: b3_intro
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 3
              capabilities: [gpu]
    tty: true